---
title: "econ_3"
author: "Lydia Bleifuss"
date: "5/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#set up 
library(tidyverse)
library(rootSolve)
library(reconPlots)
```

```{r}
#read in data
whale_data <- read.csv("HW3Data.csv")
whale_data

#1. Create a linear probability model that predicts a respondent’s probability of voting ‘yes’ on the ballot based on their age, income, NEP score, the risk reduction offered by the program, and the cost of the program to that respondent. Show the model and interpret the regression coefficients.

#create regression model:
#Show the model in a nice way (write the formal model equtaion, not with numbers or with, no worries), make a table 

#risk, coefficient estimate (round here, to 3, he doesnt care), somethign that pertains to standard error or p value

#risk 
#bid (annual payment for household, WTP/cost of program to the respondant)
#vote (0 or 1, no or yes)
#NEP (measure of environmental concern)
#income
#age

 
# A. Saturated model: contains all predictor variables 
whale_lm1 <- lm(vote ~ risk + bid + NEP + income + age , data = whale_data)
summary(whale_lm1)

summary(whale_lm1)
intercept <- whale_lm1$coefficients[1]
risk <- whale_lm1$coefficients[2]
bid <- whale_lm1$coefficients[3]
nep <- whale_lm1$coefficients[4]
income_one <- whale_lm1$coefficients[5]
income_poor <- whale_lm1$coefficients[6]
income_rich <- whale_lm1$coefficients[7]
income_veryrich <- whale_lm1$coefficients[8]
age_to50 <- whale_lm1$coefficients[9]
age_to40 <-  whale_lm1$coefficients[10]
age_to60 <-  whale_lm1$coefficients[11]
age_to30 <-  whale_lm1$coefficients[12]

#Interperet Regression Coefficients (google doc)
#Income: Middle
#Age: over sixty 


```

```{r}
#2. Based on this regression, what can you say about the value of a single prevented whale death? (Hint: Think about how risk reduction for all whales translates into the number of whale deaths avoided)

#Hints
#Solve for bid
#Risk Reduction (20%), 5 whales saved, this is a constant 

#1. Rearranged equation in terms of bid ~ other variables
#2. Multipled each calculated coefficient by 0.04 (20% / 5 whales = 4% or 0.04), determine WTP for vessel speed reduction programs from 0 - 4% 
#3. Total value to mitigate death of one whale = $2.7834

tot_ave_vote <- mean(whale_data$vote) 
tot_ave_vote # 0.714
tot_ave_nep <- mean(whale_data$NEP)
tot_ave_nep # 38.366

#Average Vote: 0.714
#Average NEP: 38.366
#Assuming age to 30 and poor income. 

#how much would your bid change due to an additional 4% risk reduction 

#0%
bid_zero <- (intercept + age_to30 + income_poor + (nep*tot_ave_nep) + (risk*0) - tot_ave_vote)/(-1*bid)

bid_zero #35.06003 

#4%
bid_four <- (intercept + age_to30 + income_poor + (nep*tot_ave_nep) + (risk*4) - tot_ave_vote)/(-1*bid)

bid_four #37.84343

wtp_one_whale <- bid_four - bid_zero
wtp_one_whale #2.7834 

#sam notes
#calculate bid for basline risk and then recalaculate for risk at x+4%

# risk_coef = whale_lm$coefficients['risk']
#a lot of them say intercept 
```

```{r}
#3. Pick three arbitrary respondents. For each of those respondents, estimate their WTP for a VSR program offering 60% risk reduction.

# Random participants chosen and their WTP for VSR Progam: 

#71: income_poor, age_to50, NEP: 27

bid_71 <- (intercept + age_to50 + income_poor + (nep*27) + (risk*60)-tot_ave_vote)/(-1*bid)
bid_71 # -101.4938

#269: income_veryrich, age_to40, NEP: 32

bid_269 <- (intercept + age_to40 + income_veryrich + (nep*32) + (risk*60)-tot_ave_vote)/(-1*bid)
bid_269 #  -14.31479 

#336: income_rich, age_to30, NEP: 55

bid_336 <- (intercept + age_to30 + income_rich + (nep*55) + (risk*60)-tot_ave_vote)/(-1*bid)
bid_336 #  327.8921 


```

```{r}
#4 Now repeat this process and estimate the mean WTP for a VSR program offering 60% risk reduction among Santa Barbara County households.

tot_ave_vote <- mean(whale_data$vote) 
tot_ave_vote # 0.714

tot_ave_nep <- mean(whale_data$NEP)
tot_ave_nep # 38.366

mode_inc <- whale_data %>% 
  count(income == "very_rich", income == "rich", income == "poor", income == "one_percent", income == "middle")

mode_inc # income_onepercent  


mode_age <- whale_data %>% 
  count(age == "tothirty", age == "toforty", age == "tofifty", age == "tosixty", age == "oversixty")

mode_age # age_to30


# Use the average NEP, income one percent, and to 30 age bracket to find the average bid in sb county 
bid_county <- (intercept + age_to30 + income_one + (nep*tot_ave_nep) + (risk*60) - tot_ave_vote)/(-1*bid)

bid_county
#  82.503
```

```{r}
#5 If there are 150,000 households in Santa Barbara County, estimate the total benefit of a VSR program to these households.

tot_ben <- bid_county*150000
tot_ben
# 12,375,410
```

```{r}
#6 Based only on these benefits, do the benefits of the VSR program outweigh the costs?

#Total Cost: 7,000,000
#Total Ben: 12,375,410
#Net Ben: 5,375,410 
```

```{r}
#INFO: When a container ship reduces its speed, it not only reduces the risk of colliding with a whale but also emits less carbon per distance traveled. For this reason, the WhaleStrikes Group Project recommended enrolling container ships in voluntary carbon trading markets to mitigate fatal whale strikes. Assume that for any ship transiting the Santa Barbara Channel, a speed reduction (that results in a 60% risk reduction) will cost the shipper $1,000, but will result in 20 fewer tons of CO2 emitted per transit.
```

```{r}
#7 Suppose the price of a carbon credit is $Z per ton, at what price Z* will the shipping industry decide to adopt the VSR for purely self-interested reasons? (Note: if ships voluntarily reduce speed, then the $7 million cost (noted above) of implementing the VSR would be avoided)

#60% risk reducition costs the shipper: 
#$1,000 to reduce by 20 tons
#$50 to reduce by 1 ton 

#at any cost of carbon credti that is less than $50 (??)

#%60 risk reduction means 15 whales saved (20% * 3)
#15 * 2.78 = WTP (not cost of 7 millions means ignore this cost)


social_value <- (wtp_one_whale*15*150000)

social_value #6262649

```

